# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2a52ce08ef26fbf6fadccfa96a51ec6a9885b9e46e2c559e703d74801eaed6aa8f4d2724d7ea64fc044d0efe7876eca6e86ec03098e858ae1b1e22ddb22a88

test:
  secret_key_base: 0d69561494678e7f9677f0de79d19f9c5991a8d7bf43a82c306d31afd7645c5ca4a94e769614f07fd60ed7842146496bb35a8964da65476a5f6999b9be188ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
